version: "3.8"

services:
  pill-box:
    container_name: pill-box
    build: .
    restart: always
    image: pill-box
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx:1.25.5
    restart: always
    volumes:
      - ./infra/configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/configs/nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"

  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./infra/volumes/postgresql:/var/lib/postgresql/data
    restart: always
